name: boilerplate
description: A new Flutter project.

version: 0.0.1+1 

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ui  widgets
  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.4
  flutter_svg: ^0.21.0+1
  pin_code_fields: ^7.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_secure_storage: ^4.1.0
  responsive_grid: ^2.0.0

  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.0.1
  shimmer: ^2.0.0

  # othe utils
  social_share: ^2.1.1
  equatable: ^2.0.0
  device_preview:

  # state management
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  rxdart: ^0.26.0
  logger: 

  # network
  flutter_downloader: ^1.6.0
  dio: ^4.0.0
  http: ^0.13.3
  connectivity: ^3.0.4

  # video 
  chewie: 

  # nottifications and firebase
  # firebase_core: ^1.1.1
  # firebase_messaging: ^10.0.0
  # flutter_local_notifications: ^5.0.0+4
  # flutter_facebook_auth: ^3.3.3+1
  # google_sign_in: ^5.0.2

  # data persistence
  shared_preferences: ^2.0.5
  moor: ^4.2.1
  sqlite3_flutter_libs: ^0.4.1

  # file system and path
  image_picker: ^0.7.4
  file_picker: ^3.0.1

  # localization
  easy_localization: ^3.0.0

#github forks

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^4.1.0
  change_app_package_name: ^1.0.0
  moor_generator:

flutter:
  assets:
    - assets/translations/
    - assets/images/

  uses-material-design: true

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
